// Generated by CoffeeScript 1.6.1
(function() {

  module.exports = function(string) {
    return "return require('tsedn').parse(\"" + (string.replace(/"/g, '\\"').replace(/\n/g, " ").trim()) + "\")";
  };

}).call(this);
